# Generated by Django 5.1.4 on 2024-12-30 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motor', models.CharField(max_length=50)),
                ('transmision', models.CharField(choices=[('Manual', 'Manual'), ('Automática', 'Automática')], max_length=50)),
                ('combustible', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diésel', 'Diésel'), ('Eléctrico', 'Eléctrico'), ('Híbrido', 'Híbrido')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('on', 'on'), ('off', 'off')], default=['on'], max_length=50)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('state', models.CharField(choices=[('on', 'on'), ('off', 'off')], default=['on'], max_length=50)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.vehicle')),
            ],
        ),
    ]
