# Generated by Django 5.1.4 on 2025-01-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='combustible',
            field=models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diésel', 'Diésel'), ('Eléctrico', 'Eléctrico'), ('Híbrido', 'Híbrido')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='marca',
            field=models.CharField(choices=[('Ford', 'Ford'), ('Fiat', 'Fiat'), ('Audi', 'Audi'), ('Renault', 'Renault')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmision',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automática', 'Automática')], max_length=20),
        ),
    ]
