# Generated by Django 5.1.4 on 2024-12-27 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
        migrations.RenameField(
            model_name='img',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
    ]
