# Generated by Django 5.1.4 on 2024-12-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_rename_vehicle_id_description_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='imagen_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
