# Generated by Django 5.1.4 on 2024-12-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_alter_vehicle_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
